import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";
import "styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fundación Domus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap"
          rel="stylesheet"
        />
        <link rel="shortcut icon" href="/logos/logodomus.jpg" />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
          integrity="sha512-CqHIvpN5AY8fr63vRfmbA6G5tJX/ugcagZBg0MmY2BV2JUxqFEE0AdhX/xBBZ59nhfFlP6+fHKpN7hqDOy4FCg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <html lang="es">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
